name: job_finetune
channels:
  - defaults
  - conda-forge
  - pytorch
  - nvidia
dependencies:
  - python=3.10
  - pytorch
  - torchvision
  - torchaudio
  - transformers
  - datasets
  - peft


# conda env create --file=URL
# conda env create -f environment.yml
# conda activate job_finetune
